# Generated by Django 5.2.9 on 2025-12-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('music', 'Music'), ('tools', 'Tools'), ('games', 'Games'), ('education', 'Education'), ('other', 'Other')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one-time', 'One-Time'), ('custom', 'Custom'), ('trial', 'Trial')], max_length=20)),
                ('renewal_date', models.DateField()),
                ('cancel_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
